### PR TITLE
adding test

### PR DESCRIPTION
**Pull request by steven2249**

### CODE REVIEW

**Comment by blasee** [comment]
Hi @steven2249,

Thanks for your help! Would you mind adding testthat to the `Suggests:` field in DESCRIPTION please? I think that will help travis pass the build?

Keep up the good work.

**Comment by blasee** [comment]
Hi @steven2249, any ideas on why some of the tests are failing the travis build?

**Comment by steven2249** [comment]
@blasee I'm still working on some tests. Probably I will finish by tonight. Sorry for that.

**Comment by steven2249** [comment]
@blasee I have finished working on all tests. Would you please have a check? Thanks!

**Comment by blasee** [comment]
Thanks for your help @steven2249!

**Pull request merged**
